### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.keras'

### ISSUE THREAD

**Issue by CesarCrZy** [kyleskom/NBA-Machine-Learning-Sports-Betting#145]
i getting following Error when running

py main.py -A -odds=fanduel

```
Traceback (most recent call last):
  File "C:\Git\NBA-Machine-Learning-Sports-Betting\main.py", line 5, in <module>
    from src.Predict import NN_Runner, XGBoost_Runner
  File "C:\Git\NBA-Machine-Learning-Sports-Betting\src\Predict\NN_Runner.py", line 6, in <module>
    from tensorflow.keras.models import load_model
ModuleNotFoundError: No module named 'tensorflow.keras'
```

**Comment by thierrytcf** [comment]
Try install the module with this code : 

`pip install keras`

**Comment by JP23000** [comment]
I am getting a similar issue:  Except mine says

  File "C:\Users\johnp\NBA-Machine-Learning-Sports-Betting\main.py", line 3, in <module>
    import tensorflow as tf
  File "C:\Users\johnp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tensorflow\__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
ModuleNotFoundError: No module named 'tensorflow.python'

**Comment by kyleskom** [comment]
I see you using Python 3.10, try 3.9.

**Comment by JP23000** [comment]
Thank you!  Actually I upgraded to 3.11 and it worked like a champ.

Also…. How would one go about retargeting this for MLB?

John

**Comment by JP23000** [comment]
Well this is completely out of the scope of my abilities.... Shit.  It is
too bad because my O/U model has been crushing it... winning 62.9% on the
O/U since the 15th playing every game.  Utilizing a Kelly ranking system
for unit distribution among the picks, and recalculating my 1% unit size
every day.  I started with $1000 on the 15th betting $10 a unit and
adjusting that every day... My 1k is up to $2800 already....

I can pay you to help me buddy!!!

**Comment by szocpaul** [comment]
what win ratio are you using in your kelly calculation?

**Comment by kyleskom** [comment]
Sorry what is the issue?

**Comment by szocpaul** [comment]
No issue. I know we should open a discussion. sorry :)
