### ISSUE TITLE
Colorada error

### ISSUE THREAD

**Issue by Sausalitos** [kyleskom/NBA-Machine-Learning-Sports-Betting#294]
Please Review, give colorama error

**Comment by Baaios** [comment]
I would advise you to check the most recent closed issues.

**Comment by Sausalitos** [comment]
Thanks for the answer, I have reviewed but I do not see anything related to this error, it is rare because before yesterday if it worked without problem.

**Comment by Baaios** [comment]
I understand you're scared because you cannot get it to work, so did i. Don't worry, to work, replace on your ColabNotebook: 

 #Bootstrap Files
Where it says:

 ! git clone https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting.git

To: 

! git clone https://github.com/chriseling/NBA-Machine-Learning-Sports-Betting.git

This is the version on 30 April.

**Comment by Sausalitos** [comment]
If it works now, thank you very much! You are very kind.

**Comment by Sausalitos** [comment]
Thanks

**Comment by Baaios** [comment]
You're welcome.

**Comment by Baaios** [comment]
If you want the latest version, replace the Bootsrap Model with the following:

**Comment by Sausalitos** [comment]
What are the differences? Could you also tell me a little bit how you do to decide the best bets? Thank you
