### ISSUE TITLE
Question on Accuracy

### ISSUE THREAD

**Issue by gstuart13** [kyleskom/NBA-Machine-Learning-Sports-Betting#334]
Hi Kyle,

Thanks again for your update on the code itself. Last night I ran a test and placed a bet on all favorites the model put out. It was a tough night with 7 wins and 13 losses. I just want to confirm that the 69% ML rate and 55% O/U rate is based on lifetime and not day over day? I'm not new to better, but certainly newer to using python based machine learning algorithms to do so (outside of course the stuff the standard sites put out). 

Not upset at all, just want to set proper expectations.

**Comment by cpjolicoeur** [comment]
You wont hit a 69% win rate each day on the ML bets if that is what you are asking.   69% is the accuracy of the trained model over the historical dataset it was trained on for the model methodology used.

**Comment by sportsfan69** [comment]
Last night was the first bad night so far for the model this season

**Comment by gstuart13** [comment]
OK I thought so. I knew there was no way that was sustainable. I appreciate
the quick response!

Out of curiosity, does the team have similar model for other sports such as
NHL, NFL, etc.? Big fan of what you all are doing. I'm newer to python and
found a great repository of NFL data going back to 1999, but not sure how
to turn it into as effective a model as to what you're doing!

**Comment by thprtm** [comment]
Did you downloaded the program or runned it via colab?

**Comment by gstuart13** [comment]
Ran it via colab.

**Comment by thprtm** [comment]
Colab is more accurate than downloading?

**Comment by gstuart13** [comment]
In what way? Sorry I don't understand the question. I did try running it in
Visual Studio. Are you saying that the model would be more accurate outside
of colab?

**Comment by cpjolicoeur** [comment]
The model accuracy wouldnt/shouldnt change no matter where you run it.  Assuming you are running the same model of course against the same inputs.

**Comment by gstuart13** [comment]
Oh sorry, everything is working great now. I just noticed that last night I
got killed when following the model and then didn't know if you had similar
models to NFL and NHL.

**Comment by zerotwenty** [comment]
I am also running in colab and since yesterday its been giving the bad date format when parsing the csv.  Assuming the date format in the csv changed from what the code was programmed for??

**Comment by zerotwenty** [comment]
As seen on other open issue thread installing this version of pandas seems to fix the bad date format
!pip3 install pandas==2.1.0

**Comment by gstuart13** [comment]
Not having issues with date format, but is anyone else noticing how far off this model has been? I'll give the caveat that I literally just started tailing this week, but the results have been nowhere near the lifetime win %. I'm assuming the model learns as the season goes un, but last night, the ML predictions went 4 and 8, while the totals went 6 and 6. If you went all in, it was a 10 and 14 night. I was looking at percentages in high 60s and above and still went backwards. 

Admittedly, I haven't done a ton with modeling like this in the past, but something just seems off to start.

**Comment by cpjolicoeur** [comment]
Several things, the overall percentages are just that - overall percentages.  You wont hit those numbers in the short term (night by night).  Some nights you will be way under, others you might hit 100% accuracy.  

Second, the new season has just started, so while the historical data is in there and modeled for the past several seasons, each new season brings changes to the tables with roster changes and all the other things that need to shake out.  Once a few weeks/months of this season have happened that data can be included in training set and will get better over time for this season.

Lastly, you can't just blindly follow the predictions, because they are just that, predictions.  You need to combine that with the knowledge you have that that model doesnt.  For example, there are a lot of injured players right now that didnt play last night.  There was a huge trade with Philly and LAC that affected things related to those teams, etc...  You gotta take that existing knowledge into account and then weigh that against what you see from what the model outputs.

**Comment by STRATZ-Ken** [comment]
First, background.  I train models daily for my real job.  Second, nothing below is here to insult Kyle or his work. What he is providing for free is a great foundation for others to use.  The fact he deals with the constant repeat of dumb questions is beyond amazing. But this is what it is, a foundation.  You cannot and will not make money with the current state this project is.  People who said they made money, well a broken clock is correct twice a day.

Lets just take a look at what the inputs are.  They are a collection of stats collected from NBA which are a sum of all the players on the team.  Has a single trade or player been added to the team since last year? Then the odds are wrong.  Is a single person hurt or taking the day off today? Then the odds are wrong.  Is the fact the model is trained with all the data from the previous year and we are in week 1 of the NBA with very little data collected for the new teams? The odds are wrong.

I truly hope this response is linked every time someone says they are winning or losing money with this.  @kyleskom is amazing for doing this, and I hope he continues to improve his models and foundation. However, please stop with the idea that you can run this blindly, take the picks and win money, it wont happen.

**Comment by cpjolicoeur** [comment]
Totally agree and second what @STRATZ-Ken is saying.  This project isnt meant to be, nor does it claim to be, an "fool-proof" accurate prediction tool.  Its a good project and nice starting point for people who are 1) ML developers, or 2) NBA betters who are ML interested.  You can take what is here, use it, learn from it, modify and tweak it for your own wants/needs.  But dont expect to just run the models and make profits guaranteed :)  Anyone telling you that is possible with any "system" or model is lying to you.  If it were that easy, the bookies would cease to exist :)

**Comment by elfrost** [comment]
I started to use week ago and thank you devs for this, very well coded and I enjoyed that.
I went into few files and I'm wondering if I need to add 23-24 in code or not and if I need to learn model once week or so?
whats is the good practice to use as per your experience?
thanks

**Comment by cpjolicoeur** [comment]
@elfrost yes, at some point you'd probably need/want to start pulling in data from the 2023-24 season and retraining model with that data.  When you do that and at what frequency is totally up to your discretion, if at all.

**Comment by gstuart13** [comment]
Hi Craig,

I truly appreciate the response. I want to be clear that nothing I am
trying to say is detrimental to Kyle and the amazing work he has done. As I
mentioned, I've never utilized a model like this in sports betting, so I
was spending a few days testing the model to see its accuracy as is. The
only reason I went down this path is because I've just heard through the
grapevine of some folks who use these learning models and have been very
successful in doing so.

Ken, I also appreciate your willingness to stand up for Kyel. However, I
would fall short of telling people they are asking dumb questions or
expecting to blindly make money. Some people are just simply asking
questions, such as myself, to understand if others have noticed something
similar in terms of how the model is performing. I am well aware of how
sports betting works and that some weeks you hit 70% of your bets and then
the next week you hit 10%. It's all an eb and flow.

At the end of the day, we are all here for the same thing, which is to take
some money back from the bookies and Vegas.

**Comment by STRATZ-Ken** [comment]
> However, I
> would fall short of telling people they are asking dumb questions or
> expecting to blindly make money.

Please check the closed issues.  This will 100% justify my comments.

**Comment by gstuart13** [comment]
Not everyone is as well versed with Github or these models. If people are
being rude with their comments, I could see your needing to jump in and
defend the work. However, some people are just asking because they simply
don't know or are looking for clarification.

Nothing I said in my comments was detrimental about the model, but simply
asking about others experiences within accuracy of the model. I think Craig
handled the comment well and it didn't really need any follow up from there.
