### ISSUE TITLE
OSError: Cannot parse keras metadata at path Models/NN_Models/Trained-Model-ML-1680133120.689445\keras_metadata.pb: Received error: Error parsing message

### ISSUE THREAD

**Issue by CesarCrZy** [kyleskom/NBA-Machine-Learning-Sports-Betting#344]
I get this error
I have python version 3.11.0

**Comment by sjx1943** [comment]
me too. Have you solved it?

**Comment by CesarCrZy** [comment]
yeah, i installed python 3.10.0 and pandas 2.1.0 and finally works

**Comment by dcpatterson87** [comment]
@CesarCrZy @kyleskom I did this and still got the same error unfortunately

**Comment by jsdanie1** [comment]
This is the same issue I'm having as well. Getting a handful of errors, this being one of them as well. (Oddly enough this works just fine on Google Colab, so not sure what the issue is in VS Code.

python3 - 3.11.7 (don't have much control of this i don't think, this one gets installed via the Microsoft Store)
python - 3.10.0 per the suggestion i downgraded to this, didn't seem to make any difference.


```powershell
Traceback (most recent call last):
  File "C:\Users\XXX\NBA-Machine-Learning-Sports-Betting\main.py", line 9, in <module>
    from src.Predict import NN_Runner, XGBoost_Runner
  File "C:\Users\XXX\NBA-Machine-Learning-Sports-Betting\src\Predict\NN_Runner.py", line 12, in <module>
    model = load_model('Models/NN_Models/Trained-Model-ML-1699315388.285516')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\saving\saving_api.py", line 262, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\XXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\saving\legacy\saved_model\load.py", line 113, in load
    raise IOError(
OSError: Cannot parse keras metadata at path Models/NN_Models/Trained-Model-ML-1699315388.285516\keras_metadata.pb: Received error: Error parsing message
```

**Comment by dcpatterson87** [comment]
Are you able to get the web app running and train the model with updated data with Colab? 

I can only get the very basic outputs to run in Colab. @jsdanie1

**Comment by jsdanie1** [comment]
Nope I had trouble getting the Update and Train model to work in Colab, which is why I initially started to switch over to VS Code. So oddly enough, half of it works on Google, and half of it works on VS Code lol I can update the Get_Data in VS code just fine. just won't run the outputs. Alot of the commands i've experimented with switching them from python to python3 instead. some work that way and some don't. 

`python3 -m Get_Data` instead of python.

**Comment by eSpadaMaddyS** [comment]
@jsdanie1 Did you solve this problem?Same error with keras_metadata. I use Python 3.10,Windows

**Comment by waynesid** [comment]
@jsdanie1
got this error in Windows, Vscode :
 raise IOError(
OSError: No file or directory found at Models/NN_Models/Trained-Model-ML-1680133120.689445
My solution:
Created a new Virtual environment for the project
run pip freeze > requirements.txt to install all libraries to the venv
created a new nn model in Train-Models folder, python -m NN_Model_ML.py  
replaced the model path in the NN_Runner.py 
run python main.py -nn -odds=fanduel
